### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by fullofcaffeine** [ccapndave/ember.hx#1]
Hi!

I'm considering using Haxe with Ember. It looks like I'll need to customize the js output a bit because of the Ember Object Model, but I'm still pretty much a beginner with Ember, and I don't have a lot experience with Haxe macros. I'm wondering what's the status of this project? Are you still using Haxe with Ember? Would it be hard to adapt this lib to work with the latest version of Emberjs?

Cheers!

**Comment by ccapndave** [comment]
Heya - I haven't touched this project for a very long time, and actually I never really ended up using Ember for a proper project (I used Angular for a while, and now React).  However, please feel free to fiddle about and see if you can make anything useful of it!

**Comment by fullofcaffeine** [comment]
Hey!

I also use Angular currently (with vanilla js). I was considering Haxe for its type safety for my next project, since it'll probably be a big and complex project.

It'd be very interesting to know why I ask why you chose Angular over Ember at the time.  And what's your current stack, React + something else? Are you still using Haxe?

Thanks in advance!

**Comment by ccapndave** [comment]
I don't quite remember why I chose angular over ember - I'm sure I had a good reason at the time :)

On my current project I am using Typescript + cyclejs which is working amazingly so far, although it's pretty cutting edge.

I also had a go using React with Typescript (which mostly works fine) and React with JS + Flow (which I couldn't get to work how I wanted).

**Comment by fullofcaffeine** [comment]
Cool, thanks for sharing!

I'll see if I can update this library, as I think Haxe with Ember would be a pretty powerful combo. By the way, are you still using Haxe? Any specific reasons you went with Typescript instead of it?

Thanks!
